name: Missions build on release tag

on:
  push:
    tags:
      - v2*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Install dependencies
        run: sudo apt-get install -y liblzo2-2 libvorbis0a libvorbisfile3 libvorbisenc2 libogg0 libuchardet0 wget

      - name: Download Mikero PBO tool
        run: wget https://mikero.bytex.digital/$(curl -Ls https://mikero.bytex.digital/Downloads | grep api | grep linux | cut -d "/" -f 2,3 | cut -d "\"" -f 1) -O ../depbo-tools.tgz

      - name: Extract PBO tool
        run: |
          cd ../
          tar xvf depbo-tools.tgz
          mv -v depbo-*/* $HOME/

      - name: Build missions
        run: |
          cd build
          export PATH=$PATH:$HOME/bin
          export LD_LIBRARY_PATH=$HOME/lib
          bash build.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PBO_files
          path: |
            build/*.pbo

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            "${{ github.ref_name }}" \
            build/*.pbo \
            --generate-notes          

      - name: Delete old releases
        uses: ui86/delete-older-releases@v1
        with:
          keep_latest: 10
          delete_tags: false
          delete_tag_pattern: "^v2..*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}